services :
  proyectos-monolito :
    container_name : proyectos-monolitico
    image : proyectos-monolitico:v1
    build :
      context : .
    ports :
      - "4001:4001"
    networks : 
      - proyectos-app
    environment :
      - MONGO_URI=${MONGO_URI}
      - PORT=4001
networks :
  proyectos-app :

